#!/bin/bash
if [ -z "$YADM_CLASS" ]; then
    YADM_CLASS=$(yadm config local.class)
fi

# Source yadm config
if [ -f "$HOME/.config/yadm/config" ]; then
    source "$HOME/.config/yadm/config"
fi

# Perform class-specific actions
if [ "$YADM_CLASS" = "WORK" ]; then
    echo "Setting up work environment for SimilarWeb"
    # Add work-specific setup here
else
    echo "Setting up personal environment"
    # Add personal setup here
fi


# Install Homebrew if it's not already installed
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Install packages from Brewfile
#brew bundle --file=~/.Brewfile

# Install Oh My Zsh if it's not already installed
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Install custom Oh My Zsh plugins
ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

# Install zsh-autosuggestions plugin
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
else
    echo "zsh-autosuggestions plugin is already installed"
fi

# Install zsh-syntax-highlighting plugin
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
else
    echo "zsh-syntax-highlighting plugin is already installed"
fi

# Install Powerlevel10k
if [ ! -d "$ZSH_CUSTOM/themes/powerlevel10k" ]; then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
    echo "Powerlevel10k theme has been installed"
else
    echo "Powerlevel10k theme is already installed"
fi

# Install sdkman
if [ ! -d "$HOME/.sdkman" ]; then
    curl -s "https://get.sdkman.io" | bash
else
    echo "sdkman is already installed"
fi

# Install bat catpuccin theme for bat
if [ ! -d "$(bat --config-dir)/themes/Catppuccin" ]; then
    curl -o "$(bat --config-dir)/themes/Catppuccin Latte.tmTheme" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme
    curl -o "$(bat --config-dir)/themes/Catppuccin Frappe.tmTheme" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme
    curl -o "$(bat --config-dir)/themes/Catppuccin Macchiato.tmTheme" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme
    curl -o "$(bat --config-dir)/themes/Catppuccin Mocha.tmTheme" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
    bat cache --build

# Setup ssh keys
ssh-keygen -t ed25519 -C "$(yadm config local.email)}" -f ~/.ssh/id_ed25519

# Add ssh-key to GitHub
# Add your SSH key to GitHub (requires GitHub CLI)
if ! command -v gh &> /dev/null; then
    brew install gh
fi
# Authenticate with GitHub CLI
gh auth login -p ssh -w
# Add the SSH key to your GitHub account
gh ssh-key add ~/.ssh/id_ed25519.pub --title "MacBook $(date +%Y-%m-%d)"

# Update yadm repository origin to use SSH
yadm remote set-url origin git@github.com:yourusername/dotfiles.git

echo "SSH key has been generated and added to GitHub. You can now clone your repositories using SSH."


# generate .gitconfig file in repos/work folder with email set to work email
git config --global user.email "$(yadm config local.email)"


# Perform class-specific actions
if [ "$YADM_CLASS" = "WORK" ]; then
    echo "Setting up work environment for SimilarWeb"

    git config --global includeIf."gitdir:$HOME/repos/work/".path "$HOME/.gitconfig-work"
    echo "[user]
        email = $(yadm config WORK.email)" > "$HOME/.gitconfig-work
        name = $(yadm config WORK.name)" > "$HOME/.gitconfig-work"
fi


# Set Zsh as the default shell
chsh -s $(which zsh)

echo "Bootstrap complete! Restart your shell to see changes."